services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail https://${DOMAIN_NAME} && curl --silent --fail https://www.${DOMAIN_NAME} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy

  wordpress:
    build: requirements/wordpress
    container_name: wordpress-php
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - URL=${URL}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS}
      - USER_MAIL=${USER_MAIL}
      - USER_ROLE=${USER_ROLE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'php -r ''exit(function_exists("mysqli_connect") ? 0 : 1);''',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build:
      context: requirements/mariadb
      args:
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
