version: "3.4"
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    container_name: wordpress-php
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'php -r ''exit(function_exists("mysqli_connect") ? 0 : 1);''',
        ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - inception

networks:
  inception:
    driver: bridge
